var blocks = []

blocks[0] = { color: 0xFFFFFF, name: 'minecraft:air' }
blocks[1] = { color: 0xCCCCCC, name: 'minecraft:stone' }
blocks[2] = { color: 0x00FF00, name: 'minecraft:grass' }
blocks[3] = { color: 0x814E29, name: 'minecraft:dirt' }
blocks[4] = { color: 0xFF00FF, name: 'minecraft:cobblestone' }
blocks[5] = { color: 0xB65915, name: 'minecraft:planks' }
blocks[6] = { color: 0xFF00FF, name: 'minecraft:sapling' }
blocks[7] = { color: 0x000000, name: 'minecraft:bedrock' }
blocks[8] = { color: 0x0000FF, name: 'minecraft:flowing_water' }
blocks[9] = { color: 0x0000FF, name: 'minecraft:water' }
blocks[10] = { color: 0xFF7E00, name: 'minecraft:flowing_lava' }
blocks[11] = { color: 0xFF7E00, name: 'minecraft:lava' }
blocks[12] = { color: 0xDBCFA9, name: 'minecraft:sand' }
blocks[13] = { color: 0xDDDDDD, name: 'minecraft:gravel' }
blocks[14] = { color: 0xFF00FF, name: 'minecraft:gold_ore' }
blocks[15] = { color: 0xFF00FF, name: 'minecraft:iron_ore' }
blocks[16] = { color: 0xFF00FF, name: 'minecraft:coal_ore' }
blocks[17] = { color: 0xB65915, name: 'minecraft:log' }
blocks[18] = { color: 0x008800, name: 'minecraft:leaves' }
blocks[19] = { color: 0xFF00FF, name: 'minecraft:sponge' }
blocks[20] = { color: 0xFF00FF, name: 'minecraft:glass' }
blocks[21] = { color: 0xFF00FF, name: 'minecraft:lapis_ore' }
blocks[22] = { color: 0xFF00FF, name: 'minecraft:lapis_block' }
blocks[23] = { color: 0xFF00FF, name: 'minecraft:dispenser' }
blocks[24] = { color: 0xDBCFA9, name: 'minecraft:sandstone' }
blocks[25] = { color: 0xFF00FF, name: 'minecraft:noteblock' }
blocks[26] = { color: 0xFF0000, name: 'minecraft:bed' }
blocks[27] = { color: 0xFF00FF, name: 'minecraft:golden_rail' }
blocks[28] = { color: 0xFF00FF, name: 'minecraft:detector_rail' }
blocks[29] = { color: 0xFF00FF, name: 'minecraft:sticky_piston' }
blocks[30] = { color: 0xFF00FF, name: 'minecraft:web' }
blocks[31] = { color: 0x00FF00, name: 'minecraft:tallgrass' }
blocks[32] = { color: 0x00FF00, name: 'minecraft:deadbush' }
blocks[33] = { color: 0xFF00FF, name: 'minecraft:piston' }
blocks[34] = { color: 0xFF00FF, name: 'minecraft:piston_head' }
blocks[35] = { color: 0xFF00FF, name: 'minecraft:wool' }
blocks[36] = { color: 0xFF00FF, name: 'minecraft:piston_extension' }
blocks[37] = { color: 0xFFFF00, name: 'minecraft:yellow_flower' }
blocks[38] = { color: 0xFF0000, name: 'minecraft:red_flower' }
blocks[39] = { color: 0xFF00FF, name: 'minecraft:brown_mushroom' }
blocks[40] = { color: 0xFF0000, name: 'minecraft:red_mushroom' }
blocks[41] = { color: 0xFF00FF, name: 'minecraft:gold_block' }
blocks[42] = { color: 0xFF00FF, name: 'minecraft:iron_block' }
blocks[43] = { color: 0xCCCCCC, name: 'minecraft:double_stone_slab' }
blocks[44] = { color: 0xCCCCCC, name: 'minecraft:stone_slab' }
blocks[45] = { color: 0xCCCCCC, name: 'minecraft:brick_block' }
blocks[46] = { color: 0xFF0000, name: 'minecraft:tnt' }
blocks[47] = { color: 0xFF00FF, name: 'minecraft:bookshelf' }
blocks[48] = { color: 0xCCCCCC, name: 'minecraft:mossy_cobblestone' }
blocks[49] = { color: 0x000000, name: 'minecraft:obsidian' }
blocks[50] = { color: 0xFF7E00, name: 'minecraft:torch' }
blocks[51] = { color: 0xFF7E00, name: 'minecraft:fire' }
blocks[52] = { color: 0xFF00FF, name: 'minecraft:mob_spawner' }
blocks[53] = { color: 0xFF00FF, name: 'minecraft:oak_stairs' }
blocks[54] = { color: 0xFF00FF, name: 'minecraft:chest' }
blocks[55] = { color: 0xFF0000, name: 'minecraft:redstone_wire' }
blocks[56] = { color: 0xFF00FF, name: 'minecraft:diamond_ore' }
blocks[57] = { color: 0xFF00FF, name: 'minecraft:diamond_block' }
blocks[58] = { color: 0xFF00FF, name: 'minecraft:crafting_table' }
blocks[59] = { color: 0xFF00FF, name: 'minecraft:wheat' }
blocks[60] = { color: 0xFF00FF, name: 'minecraft:farmland' }
blocks[61] = { color: 0xFF00FF, name: 'minecraft:furnace' }
blocks[62] = { color: 0xFF00FF, name: 'minecraft:lit_furnace' }
blocks[63] = { color: 0xFF00FF, name: 'minecraft:standing_sign' }
blocks[64] = { color: 0xFF00FF, name: 'minecraft:wooden_door' }
blocks[65] = { color: 0xFF00FF, name: 'minecraft:ladder' }
blocks[66] = { color: 0xFF00FF, name: 'minecraft:rail' }
blocks[67] = { color: 0xCCCCCC, name: 'minecraft:stone_stairs' }
blocks[68] = { color: 0xFF00FF, name: 'minecraft:wall_sign' }
blocks[69] = { color: 0xFF00FF, name: 'minecraft:lever' }
blocks[70] = { color: 0xFF00FF, name: 'minecraft:stone_pressure_plate' }
blocks[71] = { color: 0xFF00FF, name: 'minecraft:iron_door' }
blocks[72] = { color: 0xFF00FF, name: 'minecraft:wooden_pressure_plate' }
blocks[73] = { color: 0xFF00FF, name: 'minecraft:redstone_ore' }
blocks[74] = { color: 0xFF00FF, name: 'minecraft:lit_redstone_ore' }
blocks[75] = { color: 0xFF00FF, name: 'minecraft:unlit_redstone_torch' }
blocks[76] = { color: 0xFF00FF, name: 'minecraft:redstone_torch' }
blocks[77] = { color: 0xFF00FF, name: 'minecraft:stone_button' }
blocks[78] = { color: 0xFF00FF, name: 'minecraft:snow_layer' }
blocks[79] = { color: 0xFF00FF, name: 'minecraft:ice' }
blocks[80] = { color: 0xFF00FF, name: 'minecraft:snow' }
blocks[81] = { color: 0xFF00FF, name: 'minecraft:cactus' }
blocks[82] = { color: 0xFF00FF, name: 'minecraft:clay' }
blocks[83] = { color: 0xFF00FF, name: 'minecraft:reeds' }
blocks[84] = { color: 0xFF00FF, name: 'minecraft:jukebox' }
blocks[85] = { color: 0xFF00FF, name: 'minecraft:fence' }
blocks[86] = { color: 0xFF00FF, name: 'minecraft:pumpkin' }
blocks[87] = { color: 0xFF00FF, name: 'minecraft:netherrack' }
blocks[88] = { color: 0xFF00FF, name: 'minecraft:soul_sand' }
blocks[89] = { color: 0xFF00FF, name: 'minecraft:glowstone' }
blocks[90] = { color: 0xFF00FF, name: 'minecraft:portal' }
blocks[91] = { color: 0xFF00FF, name: 'minecraft:lit_pumpkin' }
blocks[92] = { color: 0xFF00FF, name: 'minecraft:cake' }
blocks[93] = { color: 0xFF00FF, name: 'minecraft:unpowered_repeater' }
blocks[94] = { color: 0xFF00FF, name: 'minecraft:powered_repeater' }
blocks[95] = { color: 0xFF00FF, name: 'minecraft:stained_glass' }
blocks[96] = { color: 0xFF00FF, name: 'minecraft:trapdoor' }
blocks[97] = { color: 0xFF00FF, name: 'minecraft:monster_egg' }
blocks[98] = { color: 0xFF00FF, name: 'minecraft:stonebrick' }
blocks[99] = { color: 0xFF00FF, name: 'minecraft:brown_mushroom_block' }
blocks[100] = { color: 0xFF00FF, name: 'minecraft:red_mushroom_block' }
blocks[101] = { color: 0xFF00FF, name: 'minecraft:iron_bars' }
blocks[102] = { color: 0xFF00FF, name: 'minecraft:glass_pane' }
blocks[103] = { color: 0xFF00FF, name: 'minecraft:melon_block' }
blocks[104] = { color: 0xFF00FF, name: 'minecraft:pumpkin_stem' }
blocks[105] = { color: 0xFF00FF, name: 'minecraft:melon_stem' }
blocks[106] = { color: 0xFF00FF, name: 'minecraft:vine' }
blocks[107] = { color: 0xFF00FF, name: 'minecraft:fence_gate' }
blocks[108] = { color: 0xFF00FF, name: 'minecraft:brick_stairs' }
blocks[109] = { color: 0xFF00FF, name: 'minecraft:stone_brick_stairs' }
blocks[110] = { color: 0xFF00FF, name: 'minecraft:mycelium' }
blocks[111] = { color: 0xFF00FF, name: 'minecraft:waterlily' }
blocks[112] = { color: 0xFF00FF, name: 'minecraft:nether_brick' }
blocks[113] = { color: 0xFF00FF, name: 'minecraft:nether_brick_fence' }
blocks[114] = { color: 0xFF00FF, name: 'minecraft:nether_brick_stairs' }
blocks[115] = { color: 0xFF00FF, name: 'minecraft:nether_wart' }
blocks[116] = { color: 0xFF00FF, name: 'minecraft:enchanting_table' }
blocks[117] = { color: 0xFF00FF, name: 'minecraft:brewing_stand' }
blocks[118] = { color: 0xFF00FF, name: 'minecraft:cauldron' }
blocks[119] = { color: 0xFF00FF, name: 'minecraft:end_portal' }
blocks[120] = { color: 0xFF00FF, name: 'minecraft:end_portal_frame' }
blocks[121] = { color: 0xFF00FF, name: 'minecraft:end_stone' }
blocks[122] = { color: 0xFF00FF, name: 'minecraft:dragon_egg' }
blocks[123] = { color: 0xFF00FF, name: 'minecraft:redstone_lamp' }
blocks[124] = { color: 0xFF00FF, name: 'minecraft:lit_redstone_lamp' }
blocks[125] = { color: 0xFF00FF, name: 'minecraft:double_wooden_slab' }
blocks[126] = { color: 0xFF00FF, name: 'minecraft:wooden_slab' }
blocks[127] = { color: 0xFF00FF, name: 'minecraft:cocoa' }
blocks[128] = { color: 0xFF00FF, name: 'minecraft:sandstone_stairs' }
blocks[129] = { color: 0xFF00FF, name: 'minecraft:emerald_ore' }
blocks[130] = { color: 0xFF00FF, name: 'minecraft:ender_chest' }
blocks[131] = { color: 0xFF00FF, name: 'minecraft:tripwire_hook' }
blocks[132] = { color: 0xFF00FF, name: 'minecraft:tripwire' }
blocks[133] = { color: 0xFF00FF, name: 'minecraft:emerald_block' }
blocks[134] = { color: 0xFF00FF, name: 'minecraft:spruce_stairs' }
blocks[135] = { color: 0xFF00FF, name: 'minecraft:birch_stairs' }
blocks[136] = { color: 0xFF00FF, name: 'minecraft:jungle_stairs' }
blocks[137] = { color: 0xFF00FF, name: 'minecraft:command_block' }
blocks[138] = { color: 0xFF00FF, name: 'minecraft:beacon' }
blocks[139] = { color: 0xFF00FF, name: 'minecraft:cobblestone_wall' }
blocks[140] = { color: 0xFF00FF, name: 'minecraft:flower_pot' }
blocks[141] = { color: 0xFF00FF, name: 'minecraft:carrots' }
blocks[142] = { color: 0xFF00FF, name: 'minecraft:potatoes' }
blocks[143] = { color: 0xFF00FF, name: 'minecraft:wooden_button' }
blocks[144] = { color: 0xFF00FF, name: 'minecraft:skull' }
blocks[145] = { color: 0xFF00FF, name: 'minecraft:anvil' }
blocks[146] = { color: 0xFF00FF, name: 'minecraft:trapped_chest' }
blocks[147] = { color: 0xFF00FF, name: 'minecraft:light_weighted_pressure_plate' }
blocks[148] = { color: 0xFF00FF, name: 'minecraft:heavy_weighted_pressure_plate' }
blocks[149] = { color: 0xFF00FF, name: 'minecraft:unpowered_comparator' }
blocks[150] = { color: 0xFF00FF, name: 'minecraft:powered_comparator' }
blocks[151] = { color: 0xFF00FF, name: 'minecraft:daylight_detector' }
blocks[152] = { color: 0xFF00FF, name: 'minecraft:redstone_block' }
blocks[153] = { color: 0xFF00FF, name: 'minecraft:quartz_ore' }
blocks[154] = { color: 0xFF00FF, name: 'minecraft:hopper' }
blocks[155] = { color: 0xFF00FF, name: 'minecraft:quartz_block' }
blocks[156] = { color: 0xFF00FF, name: 'minecraft:quartz_stairs' }
blocks[157] = { color: 0xFF00FF, name: 'minecraft:activator_rail' }
blocks[158] = { color: 0xFF00FF, name: 'minecraft:dropper' }
blocks[159] = { color: 0xFF00FF, name: 'minecraft:stained_hardened_clay' }
blocks[160] = { color: 0xFF00FF, name: 'minecraft:stained_glass_pane' }
blocks[161] = { color: 0xFF00FF, name: 'minecraft:leaves2' }
blocks[162] = { color: 0xFF00FF, name: 'minecraft:log2' }
blocks[163] = { color: 0xFF00FF, name: 'minecraft:acacia_stairs' }
blocks[164] = { color: 0xFF00FF, name: 'minecraft:dark_oak_stairs' }
blocks[165] = { color: 0xFF00FF, name: 'minecraft:slime' }
blocks[166] = { color: 0xFF00FF, name: 'minecraft:barrier' }
blocks[167] = { color: 0xFF00FF, name: 'minecraft:iron_trapdoor' }
blocks[168] = { color: 0x006600, name: 'minecraft:prismarine' }
blocks[169] = { color: 0xFF00FF, name: 'minecraft:sea_lantern' }
blocks[170] = { color: 0xFF00FF, name: 'minecraft:hay_block' }
blocks[171] = { color: 0xFF00FF, name: 'minecraft:carpet' }
blocks[172] = { color: 0xFF00FF, name: 'minecraft:hardened_clay' }
blocks[173] = { color: 0xFF00FF, name: 'minecraft:coal_block' }
blocks[174] = { color: 0xFF00FF, name: 'minecraft:packed_ice' }
blocks[175] = { color: 0xFF00FF, name: 'minecraft:double_plant' }
blocks[176] = { color: 0xFF00FF, name: 'minecraft:standing_banner' }
blocks[177] = { color: 0xFF00FF, name: 'minecraft:wall_banner' }
blocks[178] = { color: 0xFF00FF, name: 'minecraft:daylight_detector_inverted' }
blocks[179] = { color: 0xFF00FF, name: 'minecraft:red_sandstone' }
blocks[180] = { color: 0xFF00FF, name: 'minecraft:red_sandstone_stairs' }
blocks[181] = { color: 0xFF00FF, name: 'minecraft:double_stone_slab2' }
blocks[182] = { color: 0xCCCCCC, name: 'minecraft:stone_slab2' }
blocks[183] = { color: 0xFF00FF, name: 'minecraft:spruce_fence_gate' }
blocks[184] = { color: 0xFF00FF, name: 'minecraft:birch_fence_gate' }
blocks[185] = { color: 0xFF00FF, name: 'minecraft:jungle_fence_gate' }
blocks[186] = { color: 0xFF00FF, name: 'minecraft:dark_oak_fence_gate' }
blocks[187] = { color: 0xFF00FF, name: 'minecraft:acacia_fence_gate' }
blocks[188] = { color: 0xFF00FF, name: 'minecraft:spruce_fence' }
blocks[189] = { color: 0xFF00FF, name: 'minecraft:birch_fence' }
blocks[190] = { color: 0xFF00FF, name: 'minecraft:jungle_fence' }
blocks[191] = { color: 0xFF00FF, name: 'minecraft:dark_oak_fence' }
blocks[192] = { color: 0xFF00FF, name: 'minecraft:acacia_fence' }
blocks[193] = { color: 0xFF00FF, name: 'minecraft:spruce_door' }
blocks[194] = { color: 0xFF00FF, name: 'minecraft:birch_door' }
blocks[195] = { color: 0xFF00FF, name: 'minecraft:jungle_door' }
blocks[196] = { color: 0xFF00FF, name: 'minecraft:acacia_door' }
blocks[197] = { color: 0xFF00FF, name: 'minecraft:dark_oak_door' }

exports.blocks = blocks

var biomes = []
biomes[0] = 'Ocean'
biomes[1] = 'Plains'
biomes[2] = 'Desert'
biomes[3] = 'Extreme Hills'
biomes[4] = 'Forest'
biomes[5] = 'Taiga'
biomes[6] = 'Swampland'
biomes[7] = 'River'
biomes[8] = 'Nether'
biomes[9] = 'End'
biomes[10] = 'Frozen Ocean'
biomes[11] = 'Frozen River'
biomes[12] = 'Ice Plains'
biomes[13] = 'Ice Mountains'
biomes[14] = 'Mushroom Island'
biomes[15] = 'Mushroom Island Shore'
biomes[16] = 'Beach'
biomes[17] = 'Desert Hills'
biomes[18] = 'Forest Hills'
biomes[19] = 'Taiga Hills'
biomes[20] = 'Extreme Hills Edge'
biomes[21] = 'Jungle'
biomes[22] = 'Jungle Hills'
biomes[23] = 'Jungle Edge'
biomes[24] = 'Deep Ocean'
biomes[25] = 'Stone Beach'
biomes[26] = 'Cold Beach'
biomes[27] = 'Birch Forest'
biomes[28] = 'Birch Forest Hills'
biomes[29] = 'Roofed Forest'
biomes[30] = 'Cold Taiga'
biomes[31] = 'Cold Taiga Hills'
biomes[32] = 'Mega Taiga'
biomes[33] = 'Mega Taiga Hills'
biomes[34] = 'Extreme Hills+'
biomes[35] = 'Savanna'
biomes[36] = 'Savanna Plateau'
biomes[37] = 'Mesa'
biomes[38] = 'Mesa Plateau F'
biomes[39] = 'Mesa Plateau'
biomes[129] = 'Sunflower Plains'
biomes[130] = 'Desert M'
biomes[131] = 'Extreme Hills M'
biomes[132] = 'Flower Forest'
biomes[133] = 'Taiga M'
biomes[134] = 'Swampland M'
biomes[140] = 'Ice Plains Spikes'
biomes[149] = 'Jungle M'
biomes[151] = 'JungleEdge M'
biomes[155] = 'Birch Forest M'
biomes[156] = 'Birch Forest Hills M'
biomes[157] = 'Roofed Forest M'
biomes[158] = 'Cold Taiga M'
biomes[160] = 'Mega Spruce Taiga'
biomes[161] = 'Redwood Taiga Hills M'
biomes[162] = 'Extreme Hills+ M'
biomes[163] = 'Savanna M'
biomes[164] = 'Savanna Plateau M'
biomes[165] = 'Mesa (Bryce)'
biomes[166] = 'Mesa Plateau F M'
biomes[167] = 'Mesa Plateau M'

exports.biomes = biomes
